/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.lojadeinstrumentos;

import com.mycompany.cadastros.TelaCadastroProduto;
import com.mycompany.cadastros.TelaDeCadastro;
import com.mycompany.cadastros.TelaRelatorioAnalitico1;
import com.mycompany.instrumentosdao.ClientesDao;
import com.mycompany.instrumentosdao.ProdutosDao;
import com.mycompany.instrumentosdao.RelatoriosDAO;
import com.mycompany.instrumentosdao.VendasDao;
import com.mycompany.models.Clientes;
import com.mycompany.models.Produtos;
import com.mycompany.models.Relatorios;
import com.mycompany.models.Venda;
import java.awt.Color;
import java.awt.HeadlessException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author PEDRO ARTHUR
 */
public class SistemaDaFirma extends javax.swing.JFrame{

    /**
     * Creates new form NewJFrame
     */
    public SistemaDaFirma() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btgDebCred = new javax.swing.ButtonGroup();
        btgFiltroProd = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        lblCPF = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        txtNomecliente = new javax.swing.JTextField();
        btnBuscarCPF = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnBuscarNome = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        btnBuscarCliente = new javax.swing.JButton();
        txtCPFcliente = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCliente = new javax.swing.JTable();
        btnCadastrarCliente = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnAlterarCliente = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnAlterarProduto = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        lblNome1 = new javax.swing.JLabel();
        TxtProduto1 = new javax.swing.JTextField();
        btnConsultarProduto = new javax.swing.JButton();
        txtFiltrarProduto = new javax.swing.JTextField();
        btnCadastrarProduto = new javax.swing.JButton();
        btnConsultarProdutos = new javax.swing.JButton();
        btnExcluirProduto = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableProduto = new javax.swing.JTable();
        jpnRelatorio = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        lblDataInicial = new javax.swing.JLabel();
        lblDataFinal = new javax.swing.JLabel();
        btnGerarRelatorio = new javax.swing.JButton();
        jlbValorRelatório = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        DataFinalRelatorio = new com.toedter.calendar.JDateChooser();
        DataInicialRelatorio = new com.toedter.calendar.JDateChooser();
        btnDetalheRelatorio = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableRelatorio = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btnCredito = new javax.swing.JButton();
        btnDebito = new javax.swing.JButton();
        jblTotalVenda = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jblQTD = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        TxtAdicionarCliente = new javax.swing.JTextField();
        TxtPesquisaProdutos = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        btnAdicionarProdutos = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        btnChecarCliente = new javax.swing.JButton();
        btnProdutoCheck = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        txtQuantidade = new javax.swing.JTextField();
        lblVendaNumero = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblVenda = new javax.swing.JTable();
        btnAlterarCarrinho = new javax.swing.JButton();
        btnExcluirCarrinho = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Music Man");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusable(false);

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setForeground(new java.awt.Color(0, 0, 102));
        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTabbedPane1.setName(""); // NOI18N
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(844, 600));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));

        lblCPF.setText("* CPF:");

        lblNome.setText("* Nome:");

        btnBuscarCPF.setText("Buscar");
        btnBuscarCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCPFActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        jLabel2.setText("ou");

        btnBuscarNome.setText("Buscar");
        btnBuscarNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarNomeActionPerformed(evt);
            }
        });

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setBackground(new java.awt.Color(102, 0, 153));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel10)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(21, 21, 21))
        );

        btnBuscarCliente.setText("Buscar Todos");
        btnBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClienteActionPerformed(evt);
            }
        });

        try {
            txtCPFcliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNome, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNomecliente, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                            .addComponent(txtCPFcliente))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnBuscarCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscarNome, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)))
                .addGap(186, 186, 186)
                .addComponent(btnBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(138, 138, 138))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBuscarCPF)
                            .addComponent(lblCPF)
                            .addComponent(txtCPFcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNomecliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNome)
                            .addComponent(btnBuscarNome)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jTableCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Nome", "CPF", "Endereço", "Telefone", "E-mail", "Sexo", "Estado Civil", "Data Nasc.", "Cep"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableCliente);

        btnCadastrarCliente.setText("Cadastrar Cliente");
        btnCadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarClienteActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir Cliente");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnAlterarCliente.setText("Alterar Dados do Cliente");
        btnAlterarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 850, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 850, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCadastrarCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                            .addComponent(btnAlterarCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                            .addComponent(btnExcluir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCadastrarCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAlterarCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExcluir)
                .addGap(12, 12, 12))
        );

        jTabbedPane1.addTab("Clientes", jPanel3);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnAlterarProduto.setText("Alterar Dados dos Produtos");
        btnAlterarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarProdutoActionPerformed(evt);
            }
        });

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));

        lblNome1.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        lblNome1.setText("Nome produto");

        btnConsultarProduto.setText("Consultar");
        btnConsultarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarProdutoActionPerformed(evt);
            }
        });

        btnCadastrarProduto.setText("Cadastrar Novo Produto");
        btnCadastrarProduto.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnCadastrarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarProdutoActionPerformed(evt);
            }
        });

        btnConsultarProdutos.setText("Consultar todos");
        btnConsultarProdutos.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnConsultarProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarProdutosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(lblNome1)
                        .addGap(18, 18, 18)
                        .addComponent(TxtProduto1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnConsultarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCadastrarProduto)
                        .addGap(18, 18, 18)
                        .addComponent(btnConsultarProdutos, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(txtFiltrarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(12, 12, 12))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtProduto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNome1)
                    .addComponent(btnConsultarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadastrarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultarProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(147, 147, 147)
                .addComponent(txtFiltrarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnExcluirProduto.setText("Excluir Produto");
        btnExcluirProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirProdutoActionPerformed(evt);
            }
        });

        jTableProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Cor", "QTD Estoque", "Preço"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTableProduto);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4)
                    .addComponent(jPanel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnExcluirProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAlterarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAlterarProduto)
                    .addComponent(btnExcluirProduto))
                .addGap(8, 8, 8))
        );

        jTabbedPane1.addTab("Produtos", jPanel1);

        jpnRelatorio.setBackground(new java.awt.Color(255, 255, 255));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));

        lblDataInicial.setText("Data Inicial");

        lblDataFinal.setText("Data Final");

        btnGerarRelatorio.setText("Gerar Relatório");
        btnGerarRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarRelatorioActionPerformed(evt);
            }
        });

        jlbValorRelatório.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jlbValorRelatório.setText("R$: 0");

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel26.setText("Valor Total das Vendas:");

        DataFinalRelatorio.setDateFormatString("dd/MM/yyyy");

        DataInicialRelatorio.setDateFormatString("dd/MM/yyyy");

        btnDetalheRelatorio.setText("Detalhe");
        btnDetalheRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetalheRelatorioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDataInicial)
                            .addComponent(DataInicialRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(lblDataFinal))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(DataFinalRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addComponent(jlbValorRelatório, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 484, Short.MAX_VALUE)
                        .addComponent(btnGerarRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                    .addContainerGap(714, Short.MAX_VALUE)
                    .addComponent(btnDetalheRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(16, 16, 16)))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDataInicial)
                    .addComponent(lblDataFinal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(DataInicialRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DataFinalRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addComponent(jLabel26)
                .addGap(6, 6, 6)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnGerarRelatorio, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(jlbValorRelatório, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel8Layout.createSequentialGroup()
                    .addGap(141, 141, 141)
                    .addComponent(btnDetalheRelatorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(60, 60, 60)))
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));

        jTableRelatorio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Cliente", "DataVenda", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTableRelatorio);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 848, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpnRelatorioLayout = new javax.swing.GroupLayout(jpnRelatorio);
        jpnRelatorio.setLayout(jpnRelatorioLayout);
        jpnRelatorioLayout.setHorizontalGroup(
            jpnRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnRelatorioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpnRelatorioLayout.setVerticalGroup(
            jpnRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnRelatorioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Relatório Geral", jpnRelatorio);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Total:");

        btnCredito.setText("Credito");
        btgDebCred.add(btnCredito);
        btnCredito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreditoActionPerformed(evt);
            }
        });

        btnDebito.setText("Debito");
        btgDebCred.add(btnDebito);
        btnDebito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDebitoActionPerformed(evt);
            }
        });

        jblTotalVenda.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jblTotalVenda.setText("R$");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel7.setText("Quantidade de Itens");

        jblQTD.setText("0");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jblQTD)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jblTotalVenda)))
                .addGap(404, 404, 404)
                .addComponent(btnDebito, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jblTotalVenda)
                    .addComponent(btnCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDebito, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jblQTD)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        jPanel7.setForeground(new java.awt.Color(204, 204, 255));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel8.setText("Cliente:");

        TxtPesquisaProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtPesquisaProdutosActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel12.setText("Produto:");

        btnAdicionarProdutos.setText("Adicionar");
        btnAdicionarProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarProdutosActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnChecarCliente.setText("Cliente Check");
        btnChecarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChecarClienteActionPerformed(evt);
            }
        });

        btnProdutoCheck.setText("Produto Check");
        btnProdutoCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdutoCheckActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel15.setText("Quantidade");

        txtQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantidadeActionPerformed(evt);
            }
        });

        lblVendaNumero.setText("Venda Numero:");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel13))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(660, 660, 660)
                                .addComponent(lblVendaNumero)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TxtPesquisaProdutos, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                                    .addComponent(TxtAdicionarCliente))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnChecarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addComponent(btnProdutoCheck)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtQuantidade)))))
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAdicionarProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(lblVendaNumero)))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtAdicionarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnChecarCliente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtPesquisaProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnProdutoCheck)
                            .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAdicionarProdutos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        tblVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Cliente", "Id Produto", "Produto", "Cor", "Quantidade Estoque", "Preço", "Quantidade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblVenda);
        if (tblVenda.getColumnModel().getColumnCount() > 0) {
            tblVenda.getColumnModel().getColumn(0).setPreferredWidth(50);
            tblVenda.getColumnModel().getColumn(2).setPreferredWidth(170);
            tblVenda.getColumnModel().getColumn(3).setPreferredWidth(30);
            tblVenda.getColumnModel().getColumn(4).setPreferredWidth(50);
            tblVenda.getColumnModel().getColumn(5).setPreferredWidth(40);
            tblVenda.getColumnModel().getColumn(6).setPreferredWidth(20);
        }

        btnAlterarCarrinho.setText("Alterar item do Carrinho");

        btnExcluirCarrinho.setText("Excluir item do Carrinho");
        btnExcluirCarrinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirCarrinhoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnExcluirCarrinho, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAlterarCarrinho, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAlterarCarrinho)
                    .addComponent(btnExcluirCarrinho))
                .addGap(34, 34, 34))
        );

        jTabbedPane1.addTab("Vendas", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 879, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 592, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarProdutosActionPerformed
        try{
            if(TxtAdicionarCliente.getText().isEmpty()){
                TxtAdicionarCliente.requestFocus();
                
                throw new IllegalArgumentException();
                
            }
            if (TxtPesquisaProdutos.getText().isEmpty()){
                TxtPesquisaProdutos.requestFocus();
                
                throw new IllegalArgumentException();
            }
        }
        catch(IllegalArgumentException e){
            TxtAdicionarCliente.setBackground(Color.red);
            TxtPesquisaProdutos.setBackground(Color.red);
            JOptionPane.showMessageDialog(null, "Informe o nome do cliente e o nome do produto");
            throw new IllegalArgumentException();
        }
        
        recarregarVenda();
        
        
        
        
    }//GEN-LAST:event_btnAdicionarProdutosActionPerformed

    public void recarregarTabela() {
        ArrayList<Clientes> cliente = ClientesDao.ListarClientes();
         
        DefaultTableModel modelo = (DefaultTableModel) jTableCliente.getModel();
        modelo.setRowCount(0);
        
        //Para cada item na lista retornada do banco, adicionar na tabela
        for(Clientes item : cliente) {
            modelo.addRow(new String[] {
                        String.valueOf(item.getIdCliente()),
                        String.valueOf(item.getNomeCliente()),
                        String.valueOf(item.getCpfCliente()),
                        String.valueOf(item.getEndCliente()),
                        String.valueOf(item.getTelCliente()),
                        String.valueOf(item.getEmailCliente()),
                        String.valueOf(item.getSexoCliente()),
                        String.valueOf(item.getEstadoCliente()),
                        String.valueOf(item.getDataCliente()),
                        String.valueOf(item.getCepCliente())
            });
        }
        
    }
    
    public void recarregarTabelaProduto() {
        ArrayList<Produtos> produto = ProdutosDao.ListarProdutos();
         
        DefaultTableModel modelo = (DefaultTableModel) jTableProduto.getModel();
        modelo.setRowCount(0);
        
        for(Produtos item : produto) {
            modelo.addRow(new String[] {
                        String.valueOf(item.getId()),
                        String.valueOf(item.getNomeProduto()),
                        String.valueOf(item.getQtdProduto()),
                        String.valueOf(item.getValorProduto())
            });
        }
        
    }
    
    private void btnDebitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDebitoActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) tblVenda.getModel();
        String nomeCliente = "";
        int clienteid = Integer.parseInt(TxtAdicionarCliente.getText());
        ArrayList<Clientes> cliente = ClientesDao.ListarClientesVenda(clienteid);
        for (Clientes item : cliente) {
            nomeCliente = item.getNomeCliente();
        }
        int numeroVenda = VendasDao.ultimaVenda();
        int idCliente = 0;
        int idProduto = 0;
        String nomeProd = "";
        int qtd = 0;
        int precoUni = 0;
        int valorTotal = 0;
        boolean retorno = false;
        boolean vendaNova = true;
        
        
        for (int i = 0; i < modelo.getRowCount(); i++){
                idCliente = Integer.parseInt(modelo.getValueAt(i, 0).toString());
                idProduto = Integer.parseInt(modelo.getValueAt(i, 1).toString());
                nomeProd = modelo.getValueAt(i, 2).toString();
                qtd = Integer.parseInt(modelo.getValueAt(i, 6).toString());
                precoUni = Integer.parseInt(modelo.getValueAt(i, 5).toString());
                valorTotal = valorTotal + (Integer.parseInt(modelo.getValueAt(i, 5).toString()) * Integer.parseInt(modelo.getValueAt(i, 6).toString()));
                Venda venda = new Venda(qtd, nomeCliente, "Débito", nomeProd, precoUni, numeroVenda, valorTotal, idCliente, idProduto);
                if (i > 0) {
                retorno = VendasDao.SalvarVenda(venda, false);
                } else {
                    retorno = VendasDao.SalvarVenda(venda, true);
                }
        }
        
        
        
        if(retorno) {
            JOptionPane.showMessageDialog(rootPane, "Compra Cadastrada");
            atualizarCamposVenda();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Compra Não Cadastrada");
        }
    }//GEN-LAST:event_btnDebitoActionPerformed

    private void btnCreditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreditoActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) tblVenda.getModel();
        String nomeCliente = "";
        int clienteid = Integer.parseInt(TxtAdicionarCliente.getText());
        ArrayList<Clientes> cliente = ClientesDao.ListarClientesVenda(clienteid);
        for (Clientes item : cliente) {
            nomeCliente = item.getNomeCliente();
        }
        int numeroVenda = VendasDao.ultimaVenda();
        int idCliente = 0;
        int idProduto = 0;
        String nomeProd = "";
        int qtd = 0;
        int precoUni = 0;
        int valorTotal = 0;
        boolean retorno = false;
        boolean vendaNova = true;
        
        
        for (int i = 0; i < modelo.getRowCount(); i++){
                idCliente = Integer.parseInt(modelo.getValueAt(i, 0).toString());
                idProduto = Integer.parseInt(modelo.getValueAt(i, 1).toString());
                nomeProd = modelo.getValueAt(i, 2).toString();
                qtd = Integer.parseInt(modelo.getValueAt(i, 6).toString());
                precoUni = Integer.parseInt(modelo.getValueAt(i, 5).toString());
                valorTotal = valorTotal + (Integer.parseInt(modelo.getValueAt(i, 5).toString()) * Integer.parseInt(modelo.getValueAt(i, 6).toString()));
                Venda venda = new Venda(qtd, nomeCliente, "Crédito", nomeProd, precoUni, numeroVenda, valorTotal, idCliente, idProduto);
                if (i > 0) {
                retorno = VendasDao.SalvarVenda(venda, false);
                } else {
                    retorno = VendasDao.SalvarVenda(venda, true);
                }
        }
        
        
        
        if(retorno) {
            JOptionPane.showMessageDialog(rootPane, "Compra Cadastrada");
            atualizarCamposVenda();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Compra Não Cadastrada");
        }
    }//GEN-LAST:event_btnCreditoActionPerformed

    
    
    public void atualizarCamposVenda () {
        DefaultTableModel modelo = (DefaultTableModel) tblVenda.getModel();
        modelo.setRowCount(0);
        TxtAdicionarCliente.setText("");
        TxtPesquisaProdutos.setText("");
        jblTotalVenda.setText("R$: 0");
        jblQTD.setText("0");
    }
    
    private void btnGerarRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarRelatorioActionPerformed
        Date Data1 = DataInicialRelatorio.getDate();
        Date Data2 = DataFinalRelatorio.getDate();
        Relatorios relatorio = new Relatorios(Data1, Data2);
        ArrayList<Relatorios> relatorioFinal = RelatoriosDAO.ListarRelatorio(relatorio);
        int valorTotal = 0;
         
        DefaultTableModel modelo = (DefaultTableModel) jTableRelatorio.getModel();
        modelo.setRowCount(0);
        
        //Para cada item na lista retornada do banco, adicionar na tabela
        for(Relatorios item : relatorioFinal) {
            valorTotal = valorTotal + item.getValorVenda();
            modelo.addRow(new String[] {
                        String.valueOf(item.getIdVenda()),
                        String.valueOf(item.getClienteVenda()),
                        String.valueOf(item.getDataVenda()),
                        String.valueOf(item.getValorVenda())
            });
        }
         
        jlbValorRelatório.setText("R$: " + valorTotal);
        
    }//GEN-LAST:event_btnGerarRelatorioActionPerformed

    private void btnExcluirProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirProdutoActionPerformed
        int linhaSelecionada = jTableProduto.getSelectedRow();
        DefaultTableModel modelo = (DefaultTableModel) jTableProduto.getModel();
        int idExcluir = Integer.parseInt(modelo.getValueAt(linhaSelecionada, 0).toString());
        System.out.println("sql" + idExcluir);
        Boolean retorno = ProdutosDao.ExcluirProduto(idExcluir);
        
        if (retorno) {
            JOptionPane.showMessageDialog(rootPane, "Produto Excluido");
            recarregarTabelaProduto();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Falha");
        }
    }//GEN-LAST:event_btnExcluirProdutoActionPerformed

    private void btnCadastrarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarProdutoActionPerformed
        TelaCadastroProduto x = new TelaCadastroProduto();
        x.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnCadastrarProdutoActionPerformed

    private void btnConsultarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarProdutoActionPerformed
        String nomeProduto = TxtProduto1.getText();
        try{
            if(nomeProduto.isEmpty()){
                JOptionPane.showMessageDialog(null, "*Informe um valor no campo Produto.");
                TxtProduto1.requestFocus();
                throw new IllegalArgumentException();
            }
        }
        catch(IllegalArgumentException e){
            TxtProduto1.setBackground(Color.red);
        }    
         
        ArrayList<Produtos> produtos = ProdutosDao.ListarProdutos(nomeProduto);
         
        DefaultTableModel modelo = (DefaultTableModel) jTableProduto.getModel();
        modelo.setRowCount(0);
        
        //Para cada item na lista retornada do banco, adicionar na tabela
        for(Produtos item : produtos) {
            modelo.addRow(new String[] {
                        String.valueOf(item.getId()),
                        String.valueOf(item.getNomeProduto()),
                        String.valueOf(item.getCorProduto()),
                        String.valueOf(item.getQtdProduto()),
                        String.valueOf(item.getValorProduto())
            });
        }
        
        
    }//GEN-LAST:event_btnConsultarProdutoActionPerformed

    private void btnAlterarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarProdutoActionPerformed
        int linhaSelecionada = jTableProduto.getSelectedRow();
        DefaultTableModel modelo = (DefaultTableModel) jTableProduto.getModel();
        
        int idSelecionado = Integer.parseInt(modelo.getValueAt(linhaSelecionada, 0).toString());
        String nome = modelo.getValueAt(linhaSelecionada, 1).toString();
        String cor = modelo.getValueAt(linhaSelecionada, 2).toString();
        int qtdEstoque = Integer.parseInt(modelo.getValueAt(linhaSelecionada, 3).toString());
        int Preço = Integer.parseInt(modelo.getValueAt(linhaSelecionada, 4).toString());
        
        Produtos produtoAlterar = new Produtos(idSelecionado, nome, cor, qtdEstoque, Preço);
        
        TelaCadastroProduto telaAlterar = new TelaCadastroProduto(produtoAlterar);
        telaAlterar.setVisible(true);
        
        recarregarTabela();
    }//GEN-LAST:event_btnAlterarProdutoActionPerformed

    private void btnAlterarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarClienteActionPerformed
        
        int linhaSelecionada = jTableCliente.getSelectedRow();
        DefaultTableModel modelo = (DefaultTableModel) jTableCliente.getModel();
        
        int idSelecionado = Integer.parseInt(modelo.getValueAt(linhaSelecionada, 0).toString());
        String nome = modelo.getValueAt(linhaSelecionada, 1).toString();
        String cpf = modelo.getValueAt(linhaSelecionada, 2).toString();
        String endereco = modelo.getValueAt(linhaSelecionada, 3).toString();
        String telefone = modelo.getValueAt(linhaSelecionada, 4).toString();
        String email = modelo.getValueAt(linhaSelecionada, 5).toString();
        String sexo = modelo.getValueAt(linhaSelecionada, 6).toString();
        String estado = modelo.getValueAt(linhaSelecionada, 7).toString();
        String data = modelo.getValueAt(linhaSelecionada, 8).toString();
        SimpleDateFormat formatador = new SimpleDateFormat("yyyy-MM-dd");
        Date dataFormatada = null;
        
        try {
            dataFormatada = formatador.parse(data);
        } catch (ParseException ex) {
            Logger.getLogger(SistemaDaFirma.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        String cep = modelo.getValueAt(linhaSelecionada, 9).toString();
        
        Clientes clienteAlterar = new Clientes(idSelecionado, nome, cpf, endereco,
                                    telefone, email, sexo, estado, dataFormatada, cep);
        
        TelaDeCadastro telaAlterar = new TelaDeCadastro(clienteAlterar);
        telaAlterar.setVisible(true);
        
        recarregarTabela();
    }//GEN-LAST:event_btnAlterarClienteActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int linhaSelecionada = jTableCliente.getSelectedRow();
        DefaultTableModel modelo = (DefaultTableModel) jTableCliente.getModel();
        int idExcluir = Integer.parseInt(modelo.getValueAt(linhaSelecionada, 0).toString());
        
        Boolean retorno = ClientesDao.ExcluirCliente(idExcluir);
        
        if (retorno) {
            JOptionPane.showMessageDialog(rootPane, "Cliente Excluido");
            recarregarTabela();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Falha");
        }
        
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnCadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarClienteActionPerformed
        TelaDeCadastro x = new TelaDeCadastro();
        x.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnCadastrarClienteActionPerformed

    private void btnBuscarNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarNomeActionPerformed
        txtCPFcliente.setBackground(Color.white);
        try{    
            if(txtNomecliente.getText().isEmpty()){
                
                throw new IllegalArgumentException();
            }; 
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "*Informe um valor no campo Nome.");
            txtNomecliente.requestFocus();
            txtNomecliente.setBackground(Color.red);
        }
            
        String clienteSelecionado = txtNomecliente.getText();
        
        ArrayList<Clientes> clientes = ClientesDao.ListarClientes(clienteSelecionado, true);
         
        DefaultTableModel modelo = (DefaultTableModel) jTableCliente.getModel();
        modelo.setRowCount(0);
        
        //Para cada item na lista retornada do banco, adicionar na tabela
        for(Clientes item : clientes) {
            modelo.addRow(new String[] {
                        String.valueOf(item.getIdCliente()),
                        String.valueOf(item.getNomeCliente()),
                        String.valueOf(item.getCpfCliente()),
                        String.valueOf(item.getEndCliente()),
                        String.valueOf(item.getTelCliente()),
                        String.valueOf(item.getEmailCliente()),
                        String.valueOf(item.getSexoCliente()),
                        String.valueOf(item.getEstadoCliente()),
                        String.valueOf(item.getDataCliente()),
                        String.valueOf(item.getCepCliente())
            });
        }
            
    }//GEN-LAST:event_btnBuscarNomeActionPerformed

    private void btnBuscarCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCPFActionPerformed
        String cpfSelecionado = txtCPFcliente.getText();
        txtNomecliente.setBackground(Color.white);
        try {
            if (txtCPFcliente.getText().equals("   .   .   -  ")){
                throw new Exception();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Digite um CPF");
            txtCPFcliente.setBackground(Color.red);
            txtCPFcliente.requestFocus();
        }
        
      
        
        ArrayList<Clientes> clientes = ClientesDao.ListarClientes(cpfSelecionado);
         
        DefaultTableModel modelo = (DefaultTableModel) jTableCliente.getModel();
        modelo.setRowCount(0);
        
        //Para cada item na lista retornada do banco, adicionar na tabela
        for(Clientes item : clientes) {
            modelo.addRow(new String[] {
                        String.valueOf(item.getIdCliente()),
                        String.valueOf(item.getNomeCliente()),
                        String.valueOf(item.getCpfCliente()),
                        String.valueOf(item.getEndCliente()),
                        String.valueOf(item.getTelCliente()),
                        String.valueOf(item.getEmailCliente()),
                        String.valueOf(item.getSexoCliente()),
                        String.valueOf(item.getEstadoCliente()),
                        String.valueOf(item.getDataCliente()),
                        String.valueOf(item.getCepCliente())
            });
        }
    }//GEN-LAST:event_btnBuscarCPFActionPerformed

    private void TxtPesquisaProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtPesquisaProdutosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPesquisaProdutosActionPerformed

    private void btnBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClienteActionPerformed
        recarregarTabela();       
    }//GEN-LAST:event_btnBuscarClienteActionPerformed

    private void btnConsultarProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarProdutosActionPerformed
        recarregarProdutos();
    }//GEN-LAST:event_btnConsultarProdutosActionPerformed

    private void btnChecarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChecarClienteActionPerformed
        int idCliente = Integer.parseInt(TxtAdicionarCliente.getText());
        TxtAdicionarCliente.setBackground(Color.white);
        try {
            if (TxtAdicionarCliente.getText().isEmpty()){
                throw new Exception();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Digite um Id de Cliente");
            TxtAdicionarCliente.setBackground(Color.red);
            TxtAdicionarCliente.requestFocus();
        }
        
      
        
        boolean confirmaCliente = ClientesDao.ChecarCliente(idCliente);
         
        if(confirmaCliente) {
            JOptionPane.showMessageDialog(rootPane, "Cliente confirmado");
        } else {
            JOptionPane.showMessageDialog(rootPane, "Digite um Cliente Válido");
        }
    }//GEN-LAST:event_btnChecarClienteActionPerformed

    private void btnProdutoCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdutoCheckActionPerformed
        int idProduto = Integer.parseInt(TxtPesquisaProdutos.getText());
        TxtPesquisaProdutos.setBackground(Color.white);
        try {
            if (TxtPesquisaProdutos.getText().isEmpty()){
                throw new Exception();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Digite um Id de Produto");
            TxtPesquisaProdutos.setBackground(Color.red);
            TxtPesquisaProdutos.requestFocus();
        }
        
      
        
        boolean confirmaCliente = ProdutosDao.ChecarProduto(idProduto);
         
        if(confirmaCliente) {
            JOptionPane.showMessageDialog(rootPane, "Produto confirmado");
        } else {
            JOptionPane.showMessageDialog(rootPane, "Digite Um produto válido");
        }
    }//GEN-LAST:event_btnProdutoCheckActionPerformed

    private void btnExcluirCarrinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirCarrinhoActionPerformed
        int linhaSelecionada = tblVenda.getSelectedRow();
        DefaultTableModel modelo = (DefaultTableModel) tblVenda.getModel();
        modelo.removeRow(linhaSelecionada);
        JOptionPane.showMessageDialog(rootPane, "Produto Excluido");
    }//GEN-LAST:event_btnExcluirCarrinhoActionPerformed

    private void txtQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantidadeActionPerformed

    private void btnDetalheRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetalheRelatorioActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) jTableRelatorio.getModel();
        int LinhaSelecionada =jTableRelatorio.getSelectedRow();
        int idSelecionado =Integer.parseInt(modelo.getValueAt(LinhaSelecionada, 0).toString());
        
        TelaRelatorioAnalitico1 x = new TelaRelatorioAnalitico1(idSelecionado);
        x.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnDetalheRelatorioActionPerformed

    public void recarregarProdutos() {
        ArrayList<Produtos> produtos = ProdutosDao.ListarProdutos();
         
        DefaultTableModel modelo = (DefaultTableModel) jTableProduto.getModel();
        modelo.setRowCount(0);
        
        //Para cada item na lista retornada do banco, adicionar na tabela
        for(Produtos item : produtos) {
            modelo.addRow(new String[] {
                        String.valueOf(item.getId()),
                        String.valueOf(item.getNomeProduto()),
                        String.valueOf(item.getCorProduto()),
                        String.valueOf(item.getQtdProduto()),
                        String.valueOf(item.getValorProduto())
            });
        }
    }
    
    public void recarregarVenda() {
        int idProduto = Integer.parseInt(TxtPesquisaProdutos.getText());
        int idCliente = Integer.parseInt(TxtAdicionarCliente.getText());
        int qtdProduto = Integer.parseInt(txtQuantidade.getText());
        ArrayList<Produtos> produtos = ProdutosDao.ListarProdutosVenda(idProduto);
        DefaultTableModel modelo = (DefaultTableModel) tblVenda.getModel();
        int numeroVenda = VendasDao.ultimaVenda();
        lblVendaNumero.setText("Venda Numero: " + numeroVenda);
        
        //Para cada item na lista retornada do banco, adicionar na tabela
        for(Produtos item : produtos) {
            modelo.addRow(new String[] {
                        String.valueOf(idCliente),
                        String.valueOf(item.getId()),
                        String.valueOf(item.getNomeProduto()),
                        String.valueOf(item.getCorProduto()),
                        String.valueOf(item.getQtdProduto()),
                        String.valueOf(String.valueOf(item.getValorProduto())),
                        String.valueOf(qtdProduto)
            });
        }
        
        double valorTotal = 0;
        for (int i = 0; i < modelo.getRowCount(); i++) {
        valorTotal = valorTotal + Double.parseDouble(String.valueOf(modelo.getValueAt(i, 5))) * Integer.parseInt(String.valueOf(modelo.getValueAt(i, 6)));
        jblTotalVenda.setText("R$: " + valorTotal);
        }
        
        int qtdAdd = 0;
        for (int i = 0; i < modelo.getRowCount(); i++) {
        qtdAdd = qtdAdd + 1 * Integer.parseInt(String.valueOf(modelo.getValueAt(i, 6)));
        String qtd = String.valueOf(qtdAdd);
        jblQTD.setText(qtd);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SistemaDaFirma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SistemaDaFirma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SistemaDaFirma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SistemaDaFirma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SistemaDaFirma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser DataFinalRelatorio;
    private com.toedter.calendar.JDateChooser DataInicialRelatorio;
    private javax.swing.JTextField TxtAdicionarCliente;
    private javax.swing.JTextField TxtPesquisaProdutos;
    private javax.swing.JTextField TxtProduto1;
    private javax.swing.ButtonGroup btgDebCred;
    private javax.swing.ButtonGroup btgFiltroProd;
    private javax.swing.JButton btnAdicionarProdutos;
    private javax.swing.JButton btnAlterarCarrinho;
    private javax.swing.JButton btnAlterarCliente;
    private javax.swing.JButton btnAlterarProduto;
    private javax.swing.JButton btnBuscarCPF;
    private javax.swing.JButton btnBuscarCliente;
    private javax.swing.JButton btnBuscarNome;
    private javax.swing.JButton btnCadastrarCliente;
    private javax.swing.JButton btnCadastrarProduto;
    private javax.swing.JButton btnChecarCliente;
    private javax.swing.JButton btnConsultarProduto;
    private javax.swing.JButton btnConsultarProdutos;
    private javax.swing.JButton btnCredito;
    private javax.swing.JButton btnDebito;
    private javax.swing.JButton btnDetalheRelatorio;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnExcluirCarrinho;
    private javax.swing.JButton btnExcluirProduto;
    private javax.swing.JButton btnGerarRelatorio;
    private javax.swing.JButton btnProdutoCheck;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableCliente;
    private javax.swing.JTable jTableProduto;
    private javax.swing.JTable jTableRelatorio;
    private javax.swing.JLabel jblQTD;
    private javax.swing.JLabel jblTotalVenda;
    private javax.swing.JLabel jlbValorRelatório;
    private javax.swing.JPanel jpnRelatorio;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblDataFinal;
    private javax.swing.JLabel lblDataInicial;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNome1;
    private javax.swing.JLabel lblVendaNumero;
    private javax.swing.JTable tblVenda;
    private javax.swing.JFormattedTextField txtCPFcliente;
    private javax.swing.JTextField txtFiltrarProduto;
    private javax.swing.JTextField txtNomecliente;
    private javax.swing.JTextField txtQuantidade;
    // End of variables declaration//GEN-END:variables
}
